# This is a basic workflow to help you get started with Actions

name: Continuous Integration 

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "develop" branch
  pull_request:
    branches: [ "develop" ]
    
    jobs:
     build:
 
    runs-on: macos-latest
 
    steps:
    - uses: actions/checkout@v2
     
    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_13.2.1.app
     
    - name: Build and Test
      run: xcodebuild clean build test -project TodoList.xcodeproj -scheme "TodoList" -destination 'platform=iOS Simulator,name=iPhone 12' CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
